#Created by webjeda - http://webjeda.com

title: Xiruki #Keep it short
email: your@email.com
logo: http://xiruki.com/assets/images/logo.svg

baseurl: ''

sass:
 style: compressed

# Tracker
analytics: ''

### exclude the instructions / write-up in the README.md
exclude:
- README.md
